apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    name: kapacitor
  selector:
    app: kapacitor
